import { useState } from 'react';
import { format } from 'date-fns';
import { motion } from 'motion/react';
import { Calendar, PenTool, Image as ImageIcon, Sparkles } from 'lucide-react';
import { useDiaryStore } from '../../lib/store';

export function DiaryInput() {
  const { addEntry } = useDiaryStore();
  const [content, setContent] = useState('');
  const [tags, setTags] = useState<string[]>([]);
  const [tagInput, setTagInput] = useState('');
  const [mood, setMood] = useState<'magical' | 'neutral' | 'sad' | 'happy'>('magical');

  const today = new Date();
  const formattedDate = format(today, 'dd MMMM yyyy, EEEE');

  const handleAddTag = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && tagInput.trim()) {
      e.preventDefault();
      if (!tags.includes(tagInput.trim())) {
        setTags([...tags, tagInput.trim()]);
      }
      setTagInput('');
    }
  };

  const handleSubmit = () => {
    if (!content.trim()) return;

    addEntry({
      id: '', // Will be generated by store
      title: 'Daily Chronicle', // Default title, or could be extracted
      content,
      date: new Date().toISOString(),
      tags,
      mood,
      preview: '' // Will be generated
    });

    setContent('');
    setTags([]);
    setMood('magical');
    
    // Simple feedback
    // In a real app, show a toast or animation
  };

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, ease: "easeOut" }}
      className="max-w-4xl mx-auto mb-12 relative"
    >
      {/* Leather backing/binding effect */}
      <div className="absolute inset-0 bg-rusty-copper rounded-lg transform rotate-1 scale-[1.02] shadow-deep z-0"></div>
      
      {/* Main Parchment Paper */}
      <div className="relative z-10 bg-parchment p-8 rounded shadow-lg parchment-texture min-h-[300px] flex flex-col clip-path-jagged">
        
        {/* Header: Date */}
        <div className="flex justify-between items-center mb-6 border-b-2 border-rusty-copper/30 pb-2">
          <div className="flex items-center gap-3 text-burgundy font-magic text-2xl md:text-3xl">
            <Calendar className="w-6 h-6" />
            <span>{formattedDate}</span>
          </div>
          <div className="flex gap-2">
            {['magical', 'happy', 'neutral', 'sad'].map((m) => (
              <button
                key={m}
                onClick={() => setMood(m as any)}
                className={`w-8 h-8 rounded-full border-2 transition-all ${mood === m ? 'border-burgundy scale-110 shadow-md bg-gold/20' : 'border-transparent hover:bg-black/5'}`}
                title={m}
              >
                {m === 'magical' && '✨'}
                {m === 'happy' && '😊'}
                {m === 'neutral' && '😐'}
                {m === 'sad' && '😢'}
              </button>
            ))}
          </div>
        </div>

        {/* Text Area */}
        <textarea
          value={content}
          onChange={(e) => setContent(e.target.value)}
          placeholder="What magical events transpired today? (Start typing...)"
          className="w-full flex-grow bg-transparent border-none focus:ring-0 text-ink text-lg font-serif leading-relaxed resize-none outline-none placeholder:text-ink/40 min-h-[200px]"
          style={{ 
            backgroundImage: 'repeating-linear-gradient(transparent, transparent 31px, rgba(74, 69, 64, 0.1) 32px)',
            backgroundAttachment: 'local',
            lineHeight: '32px',
            paddingTop: '0'
          }}
        />

        {/* Footer: Tags & Submit */}
        <div className="mt-6 flex flex-col md:flex-row justify-between items-end gap-4">
          
          {/* Tags Input */}
          <div className="flex-1 w-full">
            <div className="flex flex-wrap gap-2 mb-2">
              {tags.map(tag => (
                <span key={tag} className="bg-gold/30 text-burgundy px-2 py-1 rounded text-sm font-bold border border-gold/50 flex items-center gap-1">
                  #{tag}
                  <button onClick={() => setTags(tags.filter(t => t !== tag))} className="hover:text-red-700">×</button>
                </span>
              ))}
            </div>
            <div className="relative">
              <input
                type="text"
                value={tagInput}
                onChange={(e) => setTagInput(e.target.value)}
                onKeyDown={handleAddTag}
                placeholder="Add tags (press Enter)..."
                className="w-full bg-transparent border-b-2 border-rusty-copper/30 focus:border-burgundy px-2 py-1 outline-none text-ink placeholder:text-ink/40 font-serif"
              />
              <Sparkles className="absolute right-2 top-1/2 -translate-y-1/2 w-4 h-4 text-gold" />
            </div>
          </div>

          {/* Actions */}
          <div className="flex items-center gap-4">
            <button 
              className="p-2 text-rusty-copper hover:text-burgundy transition-colors" 
              title="Add Image"
            >
              <ImageIcon className="w-6 h-6" />
            </button>
            
            <button
              onClick={handleSubmit}
              className="bg-burgundy text-parchment font-magic text-xl px-8 py-2 rounded shadow-md border-2 border-transparent hover:border-gold hover:shadow-magic transform hover:-translate-y-1 transition-all flex items-center gap-2 group"
            >
              <PenTool className="w-5 h-5 group-hover:rotate-12 transition-transform" />
              <span>Inscribe</span>
            </button>
          </div>

        </div>
      </div>
    </motion.div>
  );
}
